[build]
command = "npm ci && npm run build"
publish = "dist"

[build.environment_variables]
NODE_VERSION = "18"
NPM_VERSION = "9"

[[build.headers]]
for = "/*"
[build.headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
